const workspace=require('../../utils/workspace')
const core=require('../../utils/core')
Page({
 data:{filter:'all',filters:[{key:'all',text:'全部'},{key:'open',text:'未完成'},{key:'done',text:'已完成'}],notes:[],summary:'',editing:false,editId:'',form:{title:'',date:'',description:''}},
 async onShow(){await this.reload(true)},async onPullDownRefresh(){try{await this.reload(true)}finally{wx.stopPullDownRefresh()}},
 async reload(force=false){try{const p=await workspace.load(force),open=p.notes.filter(n=>!n.done).length;let list=p.notes.slice().sort((a,b)=>Number(a.done)-Number(b.done)||String(a.date||'9999').localeCompare(String(b.date||'9999')));if(this.data.filter==='open')list=list.filter(n=>!n.done);if(this.data.filter==='done')list=list.filter(n=>n.done);this.setData({summary:open+'项待办 · '+(p.notes.length-open)+'项已完成',notes:list.map(n=>Object.assign({},n,{dateText:n.date||'未设置日期'}))})}catch(e){wx.showToast({title:e.message,icon:'none'})}},
 setFilter(e){this.setData({filter:e.currentTarget.dataset.key},()=>this.reload(false))},add(){this.setData({editing:true,editId:'',form:{title:'',date:core.localISO(),description:''}})},edit(e){const id=e.currentTarget.dataset.id,n=(workspace.get().notes||[]).find(x=>x.id===id);if(n)this.setData({editing:true,editId:id,form:{title:n.title,date:n.date,description:n.description||''}})},close(){this.setData({editing:false})},
 formInput(e){const form=Object.assign({},this.data.form);form[e.currentTarget.dataset.k]=e.detail.value;this.setData({form})},dateChange(e){const form=Object.assign({},this.data.form,{date:e.detail.value});this.setData({form})},
 async save(){const f=this.data.form;if(!f.title.trim())return wx.showToast({title:'请输入标题',icon:'none'});const id=this.data.editId;await workspace.mutate(p=>{if(id){const n=p.notes.find(x=>x.id===id);if(n){n.title=f.title.trim();n.date=f.date;n.description=f.description}}else p.notes.push({id:core.uid('note'),title:f.title.trim(),date:f.date,description:f.description,done:false})});this.setData({editing:false});this.reload(false)},
 async toggleDone(e){const id=e.currentTarget.dataset.id;await workspace.mutate(p=>{const n=p.notes.find(x=>x.id===id);if(n)n.done=!n.done});this.reload(false)},
 remove(){const id=this.data.editId;wx.showModal({title:'删除事项',content:'确认删除这条事项？',success:async r=>{if(!r.confirm)return;await workspace.mutate(p=>{p.notes=p.notes.filter(x=>x.id!==id)});this.setData({editing:false});this.reload(false)}})}
})
